version: "3.9"
services:
  web:
    build:
      context: .                  # 指定构建使用的 Dockerfile 文件
    # 配置本机:容器端口映射
    ports:
      - 9000:9000
    # 挂载当前目录到www目录
    volumes:
      - .:/var/www
    # 定义容器名称
    container_name: ci4-test
    restart: always
    #环境变量
#    env_file:
#      - .env
